# Generated by Django 3.2.15 on 2023-02-10 09:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=100, unique=True)),
                ('tenant_uuid', models.UUIDField(default=uuid.uuid4)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('domain_url', models.URLField(blank=True, default=None, null=True)),
                ('schema_name', models.CharField(max_length=63, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
