# Generated by Django 3.2.15 on 2023-02-10 09:02

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snop',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 2, 10, 14, 32, 30, 35629), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2023, 2, 10, 14, 32, 30, 35629), editable=False)),
                ('created_by', models.CharField(default='default@3scsolution.com', max_length=500)),
                ('updated_by', models.CharField(default='default@3scsolution.com', max_length=500)),
                ('snop_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('snop_name', models.CharField(max_length=100)),
                ('from_date', models.DateField(default=None)),
                ('to_date', models.DateField(default=None)),
                ('demand_review_date', models.DateField()),
                ('supply_review_date', models.DateField()),
                ('pre_snop_date', models.DateField()),
                ('snop_date', models.DateField()),
                ('forecast_trigger_date', models.DateField(blank=True, null=True)),
                ('bu_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddIndex(
            model_name='snop',
            index=models.Index(fields=['bu_id', 'snop_id'], name='snop_snop_bu_id_a3296a_idx'),
        ),
    ]
