# Generated by Django 3.2.15 on 2023-02-27 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snop',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 27, 12, 57, 28, 199492), editable=False),
        ),
        migrations.AlterField(
            model_name='snop',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 27, 12, 57, 28, 199492), editable=False),
        ),
    ]
