# Generated by Django 3.2.15 on 2023-03-03 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snop', '0002_auto_20230227_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snop',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 16, 8, 28, 950179), editable=False),
        ),
        migrations.AlterField(
            model_name='snop',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 16, 8, 28, 950179), editable=False),
        ),
    ]
