# Generated by Django 3.2.15 on 2023-03-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snop', '0003_auto_20230303_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snop',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='snop',
            name='created_by',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='snop',
            name='updated_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='snop',
            name='updated_by',
            field=models.CharField(max_length=500),
        ),
    ]
