# Generated by Django 3.2.15 on 2023-03-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snop', '0004_auto_20230310_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snop',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='snop',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
