# Generated by Django 3.2.15 on 2023-03-24 12:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('snop', '0005_auto_20230315_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snop',
            name='created_by',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='snop',
            name='updated_by',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
